schema_version: 1

context:
  version: "13"

package:
  name: pipcl
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/pipcl/pipcl-${{ version }}.tar.gz
  sha256: 286aba9785463c83659a565210a82a77896195d3303bff0542e825479b56daf2

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    - packaging

tests:
  - python:
      python_version:
        - ${{ python_min }}.*
        - "*"
      imports:
        - pipcl
      pip_check: true

about:
  summary: Python packaging operations, including PEP-517 support, for use by a setup.py script.
  license: AGPL-3.0-only
  license_file: COPYING
  homepage: https://pypi.org/project/pipcl/

extra:
  recipe-maintainers:
    - soapy1
